let express = require("express")
const { colorRoutes } = require("./colorRoutes")
const { materialRoutes } = require("./materialRoutes")
const { countryRoutes } = require("./countryRoutes")
const { faqRoutes } = require("./faqRoutes")
const { categoryRoutes } = require("./categoryRoutes")
const { subcategoryRoutes } = require("./subcategoryRoutes")
const { adminAuthRoutes } = require("./adminAuthRoutes")
const { testimonialRoutes } = require("./testimonialRoutes")
const { sliderRoutes } = require("./sliderRoutes")
const { chooseRoutes } = require("./chooseRoutes")
const { productRoutes } = require("./productRoutes")
const { subsubcategoryRoutes } = require("./subSubCategoryRoutes")
let adminRoutes = express.Router()

adminRoutes.use("/color",colorRoutes)
adminRoutes.use("/material",materialRoutes)
adminRoutes.use("/country", countryRoutes)
adminRoutes.use("/faq",faqRoutes)
adminRoutes.use("/category",categoryRoutes)
adminRoutes.use("/subcategory",subcategoryRoutes)
adminRoutes.use("/adminAuth",adminAuthRoutes)
adminRoutes.use("/testimonial",testimonialRoutes)
adminRoutes.use("/slider",sliderRoutes)
adminRoutes.use("/choose",chooseRoutes)
adminRoutes.use("/product",productRoutes)
adminRoutes.use("/subsubcategory",subsubcategoryRoutes)

module.exports = {adminRoutes}